TestTask.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestTask.BLL.Interface;

namespace TestTask.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITranslationService translationService;
        public HomeController(ITranslationService translationService)
        {
            this.translationService = translationService;
        }

        public async Task<ActionResult> Index()
        {
            var translationTypes = translationService.GetList();
            return View(translationTypes);
        }
    }
}

TestTask.WEB/Controllers/TranslatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestTask.BLL.Interface;
using TestTask.BLL.DTO;
using System.Threading.Tasks;

namespace TestTask.WEB.Controllers
{
    public class TranslatorController : Controller
    {
        private readonly IRequestService translationRequestService;
        public TranslatorController(IRequestService translationRequestService)
        {
            this.translationRequestService = translationRequestService;
        }

        [HttpPost]
        public async Task<ActionResult> TranslateText(TranslationRequestDTO data)
        {
            var operationDetail = await translationRequestService.ExecuteRequestAsync(data);

            if (operationDetail.Succedeed)
            {
                operationDetail = translationRequestService.Create(data);
            }
            if (!operationDetail.Succedeed)
            {
                foreach (var error in operationDetail.Messages)
                {
                    ModelState.AddModelError(error.Property, error.Message);
                }
            }
            return PartialView(data);
        }
    }
}

TestTask.WEB/Views/Home/Index.cshtml
@model List<TestTask.BLL.DTO.TranslationTypeDTO>
@{
    ViewBag.Title = "Convert";
}
<div class="container translator-container">
    <div class="row">
        <div class="col-md">
            @using (Ajax.BeginForm("TranslateText", "Translator", new AjaxOptions { OnBegin = "OnTranslationStrat", OnComplete = "OnTranslated", OnSuccess = "OnTranslatedSuccess" }))
            {
                <div class="form-group">
                    <div class="input-group">

                        <select class="form-control" name="TranslationId" id="translatorSelect">
                            <option selected value="0"> Select translator...</option>
                            @foreach (var type in Model)
                            {
                                <option value="@type.Id">@type.Name</option>
                            }
                        </select>
                        <input class="input-group-append btn btn-dark" id="btnSubmit" type="submit" value="Convert" disabled />
                    </div>
                </div>
                <div class="translator-text-wrapper">
                    <textarea class="form-control translator-text" rows="5" name="text" placeholder="Type text here.."></textarea>
                </div>
            }
        </div>
        <div class="col-sm-12 col-md">
            <div id="result">
                @Html.Partial("../Translator/TranslateText", new TestTask.BLL.DTO.TranslationRequestDTO())
            </div>
            <div id="translating" style="display:none">
                <div class="loader"></div>
            </div>
        </div>
    </div>

</div>
@section Scripts{
    <script type="text/javascript">
        $("select").on('change', function () {
            if ($(this).find('option:selected').val() == 0)
                $("#btnSubmit").attr('disabled', true)
            else
                $("#btnSubmit").attr('disabled', false)
        });
        var loading = false;
        var fakeLoading = false;
        function OnTranslationStrat() {
            loading = true;
            fakeLoading = true;
            $("#translating").css('display', 'block');
            setTimeout(
                function () {
                    fakeLoading = false;
                    if (!loading) {
                        $("#translating").css('display', 'none');
                    }
                }, 1000);
        }
        function OnTranslated() {
            loading = false;
            if (!fakeLoading) {
                $("#translating").css('display', 'none');
            }
        }
        function OnTranslatedSuccess(data) {
            $('#result').html(data);
        }
    </script>
}

TestTask.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="body-content">
        @RenderBody()
        <footer class="footer">
            <p class="text-right">&copy; Done by Sushko Aleksandr for Advanced Field Solutions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

TestTask.WEB/Views/Translator/TranslateText.cshtml
@model TestTask.BLL.DTO.TranslationRequestDTO
<div class="translator-errors">
    <ul class="list-group">
        @foreach (ModelState modelState in ViewData.ModelState.Values)
        {
            foreach (ModelError error in modelState.Errors)
            {
                <li class="list-unstyled list-group-item-danger">
                    @error.ErrorMessage
                </li>
            }
        }
    </ul>
</div>
<div class="form-group">
<textarea rows="5" readonly class="w-100 form-control @(!String.IsNullOrEmpty(Model.ResultText)?"translator-result-success":"")">
    @Model.ResultText
</textarea>
</div>